# Site: Cuyo
# Vendor: Dell OS10
# Namespace: telegraf-sw-dell

site:
  name: cuyo
  vendor: dell-os10

replicaCount: 0

snmp:
  agents:
    # === VIEJOS (172.28.9.x) ===
    - 172.28.9.4    # PSP-CYO1-001
    - 172.28.9.5    # PSP-CYO1-002
    - 172.28.9.6    # PBL-CYO1-001
    - 172.28.9.7    # PBL-CYO1-002
    - 172.28.9.8    # PSL-CYO1-001
    - 172.28.9.9    # PSL-CYO1-002
    - 172.28.9.10   # PSL-CYO1-003
    - 172.28.9.11   # PSL-CYO1-004
    - 172.28.9.12   # PSL-CYO1-005
    - 172.28.9.13   # PSL-CYO1-006
    - 172.28.9.14   # PSL-CYO1-007
    - 172.28.9.15   # PSL-CYO1-008
    - 172.28.9.38   # PSL-CYO1-009
    - 172.28.9.39   # PSL-CYO1-010
    - 172.28.9.40   # PSL-CYO1-011
    - 172.28.9.41   # PSL-CYO1-012
    - 172.28.9.42   # PSL-CYO1-013
    - 172.28.9.43   # PSL-CYO1-014
    - 172.28.9.90   # PSL-CYO1-021
    - 172.28.9.91   # PSL-CYO1-022
    - 172.28.9.92   # PSL-CYO1-023
    - 172.28.9.93   # PSL-CYO1-024
    - 172.28.9.94   # PSL-CYO1-025
    - 172.28.9.95   # PSL-CYO1-026
    - 172.28.9.96   # PSL-CYO1-027
    - 172.28.9.97   # PSL-CYO1-028
    - 172.28.9.98   # PSL-CYO1-029
    - 172.28.9.99   # PSL-CYO1-030
    # === NUEVOS (172.29.80.x) ===
    - 172.29.80.165 # PSL-CYO1-015
    - 172.29.80.166 # PSL-CYO1-016
    - 172.29.80.167 # PSL-CYO1-017
    - 172.29.80.168 # PSL-CYO1-018
    - 172.29.80.169 # PSL-CYO1-019
    - 172.29.80.170 # PSL-CYO1-020

  tables:
    - oid: "RFC1213-MIB::sysName.0"
      name: "device"
      is_tag: true
      field: true
    - oid: "RFC1213-MIB::sysUpTime.0"
      name: "sw_sysUpTime"
      field: true
    - oid: "IF-MIB::ifTable"
    - oid: "IF-MIB::ifXTable"
    - oid: "IF-MIB::ifStackTable"
    - oid: "IF-MIB::ifRcvAddressTable"
    - oid: "HOST-RESOURCES-MIB::hrProcessorTable"
      name: "hrProcessor"
      fields:
        - oid: "HOST-RESOURCES-MIB::hrProcessorFrwID"
          name: "hrProcessorFrwID"
          is_tag: true
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10ChassisTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10CardTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10PowerSupplyTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10FanTrayTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10FanTable"

mibs:
  dirs:
    - dell-os10
    - dell

pvc:
  size: 100Mi

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
