# Site: Barracas
# Vendor: Dell OS10
# Namespace: telegraf-sw-dell

site:
  name: barracas
  vendor: dell-os10

replicaCount: 0

snmp:
  agents:
    - 172.28.9.132 # PSP-BRC1-001
    - 172.28.9.133 # PSP-BRC1-002
    - 172.28.9.134 # PBL-BRC1-001
    - 172.28.9.135 # PBL-BRC1-002
    - 172.28.9.136 # PSL-BRC1-001
    - 172.28.9.137 # PSL-BRC1-002
    - 172.28.9.138 # PSL-BRC1-003
    - 172.28.9.139 # PSL-BRC1-004
    - 172.28.9.140 # PSL-BRC1-005
    - 172.28.9.141 # PSL-BRC1-006
    - 172.28.9.142 # PSL-BRC1-007
    - 172.28.9.143 # PSL-BRC1-008
    - 172.28.9.166 # PSL-BRC1-009
    - 172.28.9.167 # PSL-BRC1-010
    - 172.28.9.168 # PSL-BRC1-011
    - 172.28.9.169 # PSL-BRC1-012
    - 172.28.9.170 # PSL-BRC1-013
    - 172.28.9.171 # PSL-BRC1-014
    - 172.29.80.48 # PSL-BRC1-015
    - 172.29.80.49 # PSL-BRC1-016
    - 172.29.80.50 # PSL-BRC1-017
    - 172.29.80.51 # PSL-BRC1-018
    - 172.29.80.52 # PSL-BRC1-019
    - 172.29.80.53 # PSL-BRC1-020
    - 172.29.80.10 # PSL-BRC1-021
    - 172.29.80.11 # PSL-BRC1-022
    - 172.29.80.108 # PSL-BRC1-023
    - 172.29.80.109 # PSL-BRC1-024
    - 172.29.80.110 # PSL-BRC1-025
    - 172.29.80.111 # PSL-BRC1-026
    - 172.28.9.213 # PSL-BRC1-027
    - 172.28.9.214 # PSL-BRC1-028
    - 172.28.9.215 # PSL-BRC1-029
    - 172.28.9.216 # PSL-BRC1-030

  tables:
    - oid: "RFC1213-MIB::sysName.0"
      name: "device"
      is_tag: true
      field: true
    - oid: "RFC1213-MIB::sysUpTime.0"
      name: "sw_sysUpTime"
      field: true
    - oid: "IF-MIB::ifTable"
    - oid: "IF-MIB::ifXTable"
    - oid: "IF-MIB::ifStackTable"
    - oid: "IF-MIB::ifRcvAddressTable"
    - oid: "HOST-RESOURCES-MIB::hrProcessorTable"
      name: "hrProcessor"
      fields:
        - oid: "HOST-RESOURCES-MIB::hrProcessorFrwID"
          name: "hrProcessorFrwID"
          is_tag: true
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10ChassisTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10CardTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10PowerSupplyTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10FanTrayTable"
    - oid: "DELLEMC-OS10-CHASSIS-MIB::os10FanTable"

mibs:
  dirs:
    - dell-os10
    - dell

pvc:
  size: 100Mi
