apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: telegraf-sw-dell
  namespace: whitecicd
spec:
  generators:
  - list:
      elements:
      - site: cuyo
        valuesFile: values-cuyo.yaml
      - site: republica
        valuesFile: values-republica.yaml
      - site: barracas
        valuesFile: values-barracas.yaml
  template:
    metadata:
      name: telegraf-{{ site }}
    spec:
      project: default
      source:
        repoURL: https://whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/telegraf-sw-dell.git
        targetRevision: main
        path: .
        helm:
          valueFiles:
          - {{ valuesFile }}
      destination:
        server: https://api.wcr-operaciones.cuyows.tcloud.ar:6443
        namespace: telemetria-switches
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
