apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf-sw-dell-root
  namespace: whitecicd
spec:
  project: default
  source:
    repoURL: https://github.com/happiolaza/telegraf-sw-dell.git
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: telemetria-switches
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
