apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf-sw-dell-root
  namespace: whitecicd
spec:
  project: default
  source:
    repoURL: https://whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/telegraf-sw-dell.git
    targetRevision: main
    path: argocd
  destination:
    server: https://api.wcr-operaciones.cuyows.tcloud.ar:6443
    namespace: telemetria-switches
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
