apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf-site.fullname" . }}
  labels:
    {{- include "telegraf-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port | default 9273 }}
    targetPort: telegraf
    protocol: TCP
    name: telegraf
    {{- if eq (.Values.service.type | default "ClusterIP") "NodePort" }}
    nodePort: {{ .Values.service.nodePort | default 0 }}
    {{- end }}
  selector:
    {{- include "telegraf-site.selectorLabels" . | nindent 4 }}
